# Generated by Django 4.0.3 on 2022-05-25 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_alter_appuser_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='otp',
            field=models.CharField(blank=True, max_length=52, null=True),
        ),
    ]
