# Generated by Django 4.0.3 on 2022-05-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_appuser_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='otp',
            field=models.CharField(default='asd', max_length=52),
        ),
    ]
