# Generated by Django 4.0.3 on 2022-05-25 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_alter_appuser_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='otp',
            field=models.CharField(max_length=52),
        ),
    ]
